build.gradle, src/main/java/uk/ac/ebi/atlas/monitoring/HealthCheckController.java, src/main/java/uk/ac/ebi/atlas/monitoring/JsonBuildVersionController.java, src/main/resources/configuration.properties, src/test/java/uk/ac/ebi/atlas/monitoring/HealthCheckControllerWIT.java
In the previous monolithic repository of EA and SCEA we added an endpoint to display some fields to know which Bamboo build no. and which branch/commit was deployed in testing, production, fallback and public servers.
After the change to Gradle we can’t pass that properties directly to the build (if Gradle can do it I don’t know how), so I’ve added them to `configuration.properties` and then they get replaced with the variable expansion in the resource processing task.
You can change that it works by passing the following VM options to Tomcat:
```-DbuildNumber=dev -DbuildBranch=dev -DbuildRevision=dev -Dtomcat.hostname=local```
With this change we have now full feature-parity with our old repo. :smiley: 
This also uses the changes from …
=> Bugfix #166430782 – Show build info in `json/build` endpoint

src/main/java/uk/ac/ebi/atlas/download/ExperimentFileType.java
File descriptions were rephrased as follows:
- Experiment metadata files (.txt) -> Experiment metadata (SDRF and IDF files archive)
- Experiment design file (.tsv) -> Experiment design file (TSV format)
- ...(MatrixMarket) -> ...(MatrixMarket archive)
- Clustering file (.tsv) -> Clustering file (TSV format)
- Marker gene files (.tsv) -> Marker gene files (TSV files archive)
=> Rephrase download files description

src/main/java/uk/ac/ebi/atlas/experiments/ExperimentsListController.java, src/test/java/uk/ac/ebi/atlas/experiments/ExperimentsListControllerWIT.java
For HCA landing page we need to show anatomograms and intended functionality we want to achieve is when a user clicks on an organism part e.g. lung then all the experiments which contain lung as an organism part are shown. Details regarding the implementation details are in following pivotal ticket:
https://www.pivotaltracker.com/story/show/169594225
=> Add param to experiments json endpoint

src/main/webapp/resources/html/hca-landing-page.html
I have created a new landing page for HCA i.e. `hca-landing-page.html` in `html` directory. Currently, the page is accessible through a URL i.e. https://{host}/gxa/sc/hca-landing-page.html.
=> Add HCA landing page

src/main/webapp/WEB-INF/jsp/tiles/views/experiment-page/experiment-description.jsp
Convert set to list before accessing random elements.
Very dumb error due to lack of typing in JSP :cry:.
=> Bugfix #170673385 – Experiments with data providers return a 500 error

src/main/java/uk/ac/ebi/atlas/hcalandingpage/JsonHcaLandingPageController.java
Companion PR of https://github.com/ebi-gene-expression-group/atlas-web-core/pull/33. Use the newly added methods in `UrlHelpers` in the HCA landing page controller.
=> Bugfix #170789143 – HCA landing page links are broken

src/main/java/uk/ac/ebi/atlas/configuration/CacheConfig.java, src/main/java/uk/ac/ebi/atlas/hcalandingpage/HcaMetadataDao.java
As the result of one part of solr stream query was larger than the default rows we set for solr query so we were missing on some of the information. Also as this query is taking a while to return the response (on my local machine it is taking around a minute). So added a cache for this method as well.
=> Fix HCA metadata endpoint and cache for for hca metada solr query

src/main/java/uk/ac/ebi/atlas/hcalandingpage/HcaHumanExperimentDao.java
As we saw in [this HCA PR](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/91) the size of the result set of solr query was similar in case of this endpoint as well so increased the number of rows to get the correct result.
=> Update row numbers for solr query

src/main/java/uk/ac/ebi/atlas/experimentpage/metadata/CellMetadataDao.java, src/main/java/uk/ac/ebi/atlas/experimentpage/metadata/CellMetadataService.java, src/main/java/uk/ac/ebi/atlas/search/GeneSearchDao.java
We were mis-labelling cells as _Not available_ because the Solr query had a row limit and the resulting map was missing many cell IDs.
I tried first to use the JSON facet API using two facets, one for `facet_characteristic_name` and another for `facet_factor_name`, since the resulting data structure bucketing by metadata value seemed more natural. However the time penalty was higher than I expected and took well over 30 seconds in big experiments, making that approach not good. You can try it yourself:
```bash
curl http://wp-np2-85:8983/solr/scxa-analytics/query -d '
rows=0&
q=*:*&
fl=cell_id,factor_value,characteristic_value&
json.facet={
cells: {
refine: true,
type: terms,
field: cell_id,
limit: -1,
domain: { filter: "experiment_accession:E-HCAD-4" }
facet: {
characteristic: {
mincount: …
```
=> Bugfix #172654192 – Values of metadata t-SNE plot are truncated

src/main/java/uk/ac/ebi/atlas/experimentpage/metadata/CellMetadataService.java, src/main/java/uk/ac/ebi/atlas/experimentpage/tabs/ExperimentPageContentService.java, src/test/java/uk/ac/ebi/atlas/experimentpage/TSnePlotSettingsServiceTest.java, src/test/java/uk/ac/ebi/atlas/experimentpage/metadata/CellMetadataServiceIT.java, src/test/java/uk/ac/ebi/atlas/experiments/ExperimentBuilder.java
We don't want to show metadata types in tsne plot dropdowns which only have 1 value.
=> Only show metadataType with 2 or more values

src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentController.java
There was an error in rendering because requests to URLs such as `http://localhost:8080/gxa/sc/json/experiments/E-GEOD-99058/resources/SUPPLEMENTARY_INFORMATION` returned a 500 error.
The request mapping method is returning a String which is interpreted as a Spring MVC view becuase the `@ResponseBody` annotation is missing (compare with bulk Expression Atlas). I replaced `@Controller` with `@RestController` to implicitly add `@ResponseBody`.
=> Bugfix #174786171 – Supplementary Information tab is broken

README.md, build.gradle, docker-compose.yaml, docker-compose.yml, docker/Dockerfile, docker/docker-compose.yml, docker/scxa-solrcloud-bootstrap-entrypoint.sh, docker/tomcat-users.xml, src/main/resources/configuration.properties
Docker Compose files and scripts to easily bring up a Single Cell Expression Atlas instance with all necessary services, plus documentation on how to populate Postgres and SolrCloud with test data sets.
=> Chore – Containerise SCXA for development

src/main/java/uk/ac/ebi/atlas/configuration/CacheConfig.java, src/main/java/uk/ac/ebi/atlas/experimentimport/ScxaExperimentCrud.java, src/main/java/uk/ac/ebi/atlas/experiments/ExperimentsListController.java
Mitch reported that /json/experiments endpoint was taking ~4 secs to return the experiment list. Upon investigation of the code, it was found that the results were not being cached. I added a new cache and also evicted it at the proper places in the experiment CRUD to keep the results consistent.
=> Optimise /json/experiments endpoint

src/main/javascript/bundles/experiment-page/src/results/AnatomogramCellTypeHeatmapView.js
I expanded the views which weren’t covered by a single ontology ID to the correspondin arrays and passed a set of values in the request parameter `organismPart`.
=> Feature #176761932 – Send multiple onotology uris to back end

src/main/java/uk/ac/ebi/atlas/experimentpage/markergenes/MarkerGeneService.java, src/main/java/uk/ac/ebi/atlas/experimentpage/tabs/ExperimentPageContentService.java, src/test/java/uk/ac/ebi/atlas/experimentpage/tabs/ExperimentPageContentServiceIT.java, src/test/java/uk/ac/ebi/atlas/experimentpage/tabs/ExperimentPageContentServiceTest.java
For experiments with incomplete anatomogram data, they should not display anatomograms. See issue here:
https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/127
=> Hide Anatomogram with incomplete data

src/main/java/uk/ac/ebi/atlas/bioentity/properties/ExpressedBioentityFinderImpl.java, src/main/java/uk/ac/ebi/atlas/configuration/AppConfig.java, src/main/java/uk/ac/ebi/atlas/search/JsonBioentityInformationController.java, src/test/java/uk/ac/ebi/atlas/bioentity/properties/ExpressedBioentityFinderImplIT.java, src/test/java/uk/ac/ebi/atlas/configuration/TestConfig.java, src/test/java/uk/ac/ebi/atlas/download/ExperimentFileLocationServiceIT.java, src/test/java/uk/ac/ebi/atlas/experimentimport/ScxaExperimentCrudIT.java, src/test/java/uk/ac/ebi/atlas/experimentpage/JsonCellMetadataControllerWIT.java, src/test/java/uk/ac/ebi/atlas/experimentpage/JsonTSnePlotControllerWIT.java, src/test/java/uk/ac/ebi/atlas/home/HomeControllerWIT.java, src/test/java/uk/ac/ebi/atlas/home/JsonExperimentsSummaryControllerWIT.java, src/test/java/uk/ac/ebi/atlas/home/JsonSpeciesSummaryControllerWIT.java, src/test/java/uk/ac/ebi/atlas/search/GeneSearchDaoIT.java, src/test/java/uk/ac/ebi/atlas/search/JsonBioentityInformationControllerWIT.java
Companion PR of https://github.com/ebi-gene-expression-group/atlas-web-core/pull/59 and https://github.com/ebi-gene-expression-group/atlas-web-core/pull/60.
This is basically some code reorganisation as a change in a couple of classes that were promoted to Spring beans, which meant thtat there need to be implementation candidates in the project or we’ll have compilation errors. However, this hasn’t been a smooth path since I encountered a very weird test interaction between `HomeControllerWIT` and `JsonExperimentsSummaryControllerWIT`. Which took me on an unexepcted road in `atlas-web-core` to refactor code here and there so that we have fewer tests that depend on `bulk-analytics` or `gene2experiment` collections. Since we now run SolrCloud on Docker Compose and one of those two …
=> Chore – Make analytics index build more robust

src/main/java/uk/ac/ebi/atlas/hcalandingpage/HcaHumanExperimentsController.java
We had an issue where when an experiment could not be found in the db the endpoint threw a `404` error which was not useful at all. So now if such a scenario occurs, the endpoint would throw a `503` error.
=> Let HCA endpoint fail gracefully

app/src/main/java/uk/ac/ebi/atlas/experimentpage/JsonTSnePlotController.java, app/src/test/java/uk/ac/ebi/atlas/experimentpage/JsonTSnePlotControllerWIT.java, app/src/test/java/uk/ac/ebi/atlas/experimentpage/tabs/ExperimentPageContentServiceIT.java, app/src/test/java/uk/ac/ebi/atlas/experimentpage/tsneplot/TSnePlotDaoIT.java, app/src/test/resources/fixtures/scxa_analytics-fixture.sql, buildSrc/src/main/groovy/atlas-web-app.java-conventions.gradle
I fixed the default value of the request parameter to be `umap` is none is specified, but I also noticed that [the front end component was using the request parameter `method` and not `plotType`](https://github.com/ebi-gene-expression-group/atlas-components/blob/master/packages/scxa-tsne-plot/src/TSnePlotView.js#L60); with these changes the expression plot should be fine. I added a test just in case.
In order to start working towards a set of passing tests I removed all references to the table `scxa_tsne` and fixed one of the fixtures. [Please see the accompanying PR in `atlas-web-core`](https://github.com/ebi-gene-expression-group/atlas-web-core/pull/64).
=> Bugfix #178913760 – Chore #176996671 – Render t-SNE plot when no gene ID is passed

app/src/main/java/uk/ac/ebi/atlas/experimentpage/tabs/ExperimentPageContentService.java
Minor fix for the issue mentioned here: https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/183
=> Add two experiments to Anatomogram blacklist

app/src/main/java/uk/ac/ebi/atlas/experimentpage/metadata/CellMetadataDao.java
Rather than showing a cryptic 400 error we use the placeholder “Not available” for missing metadata values. I haven’t included a test because:
- We need to use an incorrect condensed SDRF file
- Verifying that the logger adds an error message would mean a mocked logger, a spy, or a somewhat convoluted constructor just for the sake of testing
In summary: testing a side effect as a consequence of an edge case doesn’t seem like the most solid business logic and should happen rarely.
=> Bugfix #177533187 – Log an error if a metadata value is missing

Jenkinsfile, jenkins-k8s-pod.yaml
After many trials and errors we got it. See the results: http://45.88.81.188:30004/jenkins/view/Expression%20Atlas%20web%20apps/job/Single%20Cell%20Expression%20Atlas/job/k8s-jenkins/
At the moment you’ll see that `FileDownloadControllerWIT` is explicitly disabled. We’ll eventually need to review this test.
=> Chore #179298051-#177741644 – Test and build web app on Jenkins

app/src/main/java/uk/ac/ebi/atlas/experimentpage/markergenes/HighchartsHeatmapAdapter.java, app/src/test/java/uk/ac/ebi/atlas/experimentpage/markergenes/HighchartsHeatmapAdapterTest.java, docker/docker-compose-gradle.yml
We suffered a regression after adding the cell group tables to our DB. Before we only picked the marker gene in the group/cluster in which it had the lowest p-value. The merge now is done on the back end code, at serialisation time, since it’s a visualisation decision.
I also added some volumes to cache Gradle artifacts to speed up builds.
=> Feature #179903156 – Merge same marker gene to one row

app/src/main/javascript/bundles/experiment-page/html/index.html, app/src/main/javascript/bundles/experiment-page/src/TSnePlotViewRoute.js
TSne plot was not being correctly coloured when going through a URL. Details are in this [story](https://www.pivotaltracker.com/story/show/180331840).
The reason was that by default if there are cell types in the metadata prop then `metadata` was chosen as a default category to colour plots without checking the params passed in the URL. The issue has been resolved by checking URL params first to see if colourBy param is an integer or not and then selecting proper colourBy category.
=> Refactor to correctly select colourBy category

.github/workflows/web-app-pr.yaml, app/src/main/java/uk/ac/ebi/atlas/configuration/AppConfig.java, app/src/test/java/uk/ac/ebi/atlas/configuration/TestConfig.java, buildSrc/src/main/groovy/atlas-web-app.java-conventions.gradle
This PR adapts this repo to the changes I introduced in Atlas web core. Artifactory URL was pointing to older IP. There are more compilation errors that need to be fixed with the newer atlas-web-core.
=> Update to latest atlas-web-core, fix artifactory
